# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vladimir Soldatov's space
email: solardatov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mr. Robot: No rest for the wicked.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://soldatov.org" # the base hostname & protocol for your site
linkedin_username: vsoldatov
github_username:  solardatov
twitter_username: solardatov

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
